CREATE DATABASE ssh;

\c ssh;

CREATE TABLE ip (
	id SERIAL PRIMARY KEY,
	address VARCHAR(45),
	identifier VARCHAR(32),
	service VARCHAR(45),
	tarpit VARCHAR(10),
	time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	timespan INTERVAL);

CREATE USER ssh;
GRANT SELECT, INSERT, UPDATE ON ip TO ssh;
GRANT USAGE, SELECT ON SEQUENCE ip_id_seq TO ssh;
